\"
\" lama.man
\" 
\" Made by Tatam
\" Login   <tatam@protonmail.com>
\" 
\" Started on  Fri Oct 14 21:03:12 2016 Tatam
\" Last update Sun Jan  7 10:56:44 2018 Tatam
\"
.TH man 1 "18 Nov 2017" "1.0" "lama man page"
.SH NAME
lama \- mix a given word list to generate password dictionnary
.SH SYNOPSIS
lama [MIN] [MAX] [FILE] [OPTION]...
.SH DESCRIPTION
Lama is a tool for mixing a word list.

The goal is to obtain a custom password dictionary to a particular target, whether physical or moral.

It is therefore important that the words in this list correspond to the target.

Keep in mind that the Lama generates a simple password list and not complex, this goal is to be fast and targeted rather than slow and exostif.
.SH OPTIONS

.BR file 
    File containing all the personal words of the target.

.BR <min>
    Minimum interval number of output word (1-9).

.BR <max>
    Maximum interval number of output word (1-9).

.BR -h
    Display output informations as Human readable format. Informations will displayed on STDERR. The output size of the dictionary is approximate.

.BR -n
    Print password without transformation, as the case in the word list.

.BR -c
    Print password with the first letter capitalized if it is a letter.

.BR -C
    Print password with the first letter capitalized of each words if it is a letter.

.BR -L
    Print password with leet speak transformation. The leet speak configuration can be set at /etc/lama/leet.lst.
    
.BR -S
    Add specials characters to the words given list. The specials list characters can be edit at /etc/lama/special.lst. Note that this option directly adds a set of words to the initial list. Therefore, to get a password of type "alice_bob" where the "_" is part of -S, it is necessary to have an interval of 3.

.BR -N
    Add numeric sequences to the words given list. The numeric list characters can be edit at /etc/lama/numeric.lst. Note that this option directly adds a set of words to the initial list. Therefore, to get a password of type "alicebob1234" where the "1234" is part of -N, it is necessary to have an interval of 3.

.BR -y
    Force the answer to 'y' (yes) before the passwords generation. Be carfull, lama will generate passwords even if there is not enough space on your disk.

.SH EXAMPLES
    lama 1 4 wordlist.lst -n
    lama 2 2 wordlist.lst -nh > dictionnary.lst
    lama 2 5 wordlist.lst -n -c -C > dictionnary.lst
    lama 1 2 wordlist.lst -L > dictionnary.lst
    lama 1 4 wordlist.lst -nLSh > dictionnary.lst

.SH BUGS
When -c and -C options are used in the same time, this creates duplicates passwords on the first generation interval (the min value). This bug is assumed because to solve it would slow down the generation considerably.
.SH AUTHOR
Tatam (tatam@protonmail.com)
